# Generated by Django 4.0.2 on 2022-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meetups', '0003_location_meetup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, to='app_meetups.Participant'),
        ),
    ]
